#- env:
#        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
#          value: my-cluster-zookeeper-client:2181
#        - name: SCHEMA_REGISTRY_HOST_NAME
#          value: registry-0.schema.default.svc.cluster.local
#        - name: SCHEMA_REGISTRY_LISTENERS
#          value: http://0.0.0.0:8081
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kafka
  name: akhq-secrets
  labels:
    app.kubernetes.io/name: akhq-secrets
data:
  application-secrets.yml: |
    akhq:
      connections:
        kafka-cluster:
          key: kafka-cluster
          properties:
            bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
          schema-registry:
            url: "http://confluent-schema-registry:8081"
#          connect:
#            - name: adp-connect s
#              url: "adp-connect-cluster-connect-api:8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  name: akhq
  labels:
    app: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/prometheus'
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: secrets
            - name: MICRONAUT_CONFIG_FILES
              value: /app/application-secrets.yml
          volumeMounts:
              mountPath: /app/application-secrets.yml
              subPath: application-secrets.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8081
              path: /health
          resources:
            limits:
              memory: 1024Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 10m
      volumes:
        - name: secrets
          configMap:
            name: akhq-secrets
      imagePullSecrets:
        - name: docker-cfg
---
apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: akhq
  labels:
    app: akhq
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
    - name: info
      port: 8081
  selector:
    app: akhq

