#AKHQ_CONFIGURATION: |
#       akhq:
#         connections:
#           docker-kafka-server:
#             properties:
#               bootstrap.servers: "kafka:9092"
#               #bootstrap.servers: "3.237.253.154:9092"
#               schema-registry:
#               url: "http://schema-registry:8085"
#             connect:
#               - name: "connect"
#                 url: "http://connect:8083"

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kafka
  name: akhq-secrets
  labels:
    app.kubernetes.io/name: akhq-secrets
data:
  application-secrets.yml: |
    akhq:
      connections:
        kafka-cluster:
          key: kafka-cluster
          properties:
            bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
            security.protocol: PLAINTEXT
          schema-registry:
            url: "http://confluent-schema-registry:8081"
#          connect:
#            - name: adp-connect
#              url: "adp-connect-cluster-connect-api:8083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kafka
  name: akhq
  labels:
    app: akhq
data:
  application.yml: |
    akhq:
      server:
        access-log:
          enabled: true
          name: org.akhq.log.access
      topic:
        default-view: HIDE_INTERNAL_STREAM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  name: akhq
  labels:
    app: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
#      annotations:
#        prometheus.io/scrape: 'true'
#        prometheus.io/port: '8081'
#        prometheus.io/path: '/prometheus'
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: secrets
            - name: MICRONAUT_CONFIG_FILES
              value: /app/application.yml,/app/application-secrets.yml
          volumeMounts:
            - name: config
              mountPath: /app/application.yml
              subPath: application.yml
            - name: secrets
              mountPath: /app/application-secrets.yml
              subPath: application-secrets.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              port: 8081
#              path: /health
          resources:
            limits:
              memory: 1024Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 10m
      volumes:
        - name: config
          configMap:
            name: akhq
        - name: secrets
          configMap:
            name: akhq-secrets
      imagePullSecrets:
        - name: docker-cfg
---
apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: akhq
  labels:
    app: akhq
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
    - name: info
      port: 8081
  selector:
    app: akhq

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kafka
  name: akhq
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: akhq.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: akhq
            port:
              number: 8080
