apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
          #      - name: external
          #        port: 9094
          #        type: nodeport
          #        tls: false
          #        configuration:
          #          bootstrap:
          #            nodePort: 32000
          #          brokers:
          #            - broker: 0
          #              nodePort: 32001
          #              advertisedHost: kafka-local
          #            - broker: 1
          #              nodePort: 32002
          #              advertisedHost: kafka-local
          #            - broker: 2
          #              nodePort: 32003
          #              advertisedHost: kafka-local
      - name: external
        port: 32000
        type: ingress
        tls: false
        configuration:
          bootstrap:
            host: kafka-local
          brokers:
            - broker: 0
              host: 1.kafka-local
            - broker: 1
              host: 2.kafka-local
            - broker: 2
              host: 3.kafka.local
    #        authentication:
    #          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.1"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: { }
    userOperator: { }
