apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  labels:
    app: nginx
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.0.1
        ports:
        - containerPort: 8081
        env:
          - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
            value: MY_CLUSTER_ZOOKEEPER_CLIENT_SERVICE_HOST:2181
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: registry-0.schema.default.svc.cluster.local
          - name: SCHEMA_REGISTRY_LISTENERS
            value: http://0.0.0.0:8081
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: schema-registry
#  labels:
#    app: schema-registry
#  namespace: kafka
#spec:
#  selector:
#    matchLabels:
#      app: schema-registry
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        name: schema-registry
#    spec:
#      containers:
#      - env:
#        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
#          value: my-cluster-zookeeper-client:2181
#        - name: SCHEMA_REGISTRY_HOST_NAME
#          value: registry-0.schema.default.svc.cluster.local
#        - name: SCHEMA_REGISTRY_LISTENERS
#          value: http://0.0.0.0:8081
#        name: schema-registry
#        image: confluentinc/cp-schema-registry:5.0.1
#        ports:
#        - containerPort: 8081
#      restartPolicy: Always
